- name: Install required system packages for docker
  apt:
    name: ['apt-transport-https','ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'python3-setuptools']
    state: present
    update_cache: yes

- name: Add docker gpg apt key
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present

- name: Add docker repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present
    update_cache: yes

- name: Install docker-ce
  apt:
    name: docker-ce
    state: latest

- name: Install docker and docker-compose modules for python
  pip:
    name: ['docker', 'docker-compose']

- name: Install docker-compose from official repository
  get_url:
    url: "https://github.com/docker/compose/releases/download/v2.4.1/docker-compose-linux-x86_64"
    dest: /usr/local/bin/docker-compose
    mode: '+x'
